// Synthetic UI checks; no live Reddit credentials or writes.
const { execFileSync } = require("node:child_process");
const assert = require("node:assert/strict");
const { listing, thread } = require("./browser-fixtures.cjs");
const origin = process.argv[2] || "http://localhost:30710";
const run = (...args) => execFileSync("agent-browser", ["--session", "troddit-polish", ...args], { encoding: "utf8", timeout: 60000, env: { ...process.env, AGENT_BROWSER_ARGS: "--disable-web-security" } });
const evaluate = code => JSON.parse(run("eval", code));
const wait = code => run("wait", "--fn", `Boolean(${code})`);
const click = name => run("find", "role", "button", "click", "--name", name, "--exact");
let checks = 0;
const check = (code, message) => { assert.ok(evaluate(code), message); console.log(`PASS ${message}`); checks++; };
try {
  run("open", `${origin}/settings`);
  run("network", "route", "*/api/auth/session", "--body", "{}");
  run("network", "route", "*reddit.com*/comments/*", "--body", JSON.stringify(thread));
  run("network", "route", "*reddit.com*", "--body", JSON.stringify(listing));
  run("set", "viewport", "1440", "1100");
  wait("document.querySelector('.palette-choice')");
  for (const name of ["Meadow", "Linen", "Rosewater", "Arctic", "Lavender", "Forest", "Espresso", "Abyss", "OLED", "Dracula", "Nord", "Ocean", "Palenight"]) {
    click(`${name} theme`);
    check(`document.querySelector('.palette-choice[aria-pressed=true]').getAttribute('aria-label') === '${name} theme' && getComputedStyle(document.documentElement).getPropertyValue('--background').trim().startsWith('#')`, `${name} palette applies`);
  }
  click("Espresso theme");
  click("Blue");
  run("focus", '[aria-label="Reading text size"]'); run("press", "End");
  run("focus", '[aria-label="Reading line spacing"]'); run("press", "End");
  run("select", '.reading-tuners select:first-of-type', "serif");
  run("select", '.reading-tuners label:last-child select', "compact");
  check("getComputedStyle(document.querySelector('.reading-sample p')).fontSize === '20px' && getComputedStyle(document.querySelector('.reading-sample p')).lineHeight === '39px'", "Reading preview reflects maximum size and line spacing");
  run("reload"); wait("document.querySelector('.reading-sample') && getComputedStyle(document.querySelector('.reading-sample p')).fontSize === '20px'");
  check("JSON.parse(localStorage.getItem('troddit:appearance')).font === 'serif' && document.documentElement.dataset.theme === 'espresso'", "Palette and tuning survive reload");
  click("Toggle light and dark theme");
  check("document.documentElement.dataset.theme === 'light'", "Custom dark palette toggles to light");
  click("Linen theme");
  run("open", origin); wait("document.querySelector('.post-card')");
  check("getComputedStyle(document.querySelector('.reading-body')).fontSize === '20px' && getComputedStyle(document.querySelector('.post-card-content')).paddingTop === '14px'", "Reading and density tuning reach real feed cards");
  wait("Array.from(document.images).every(image => image.complete)");
  run("wait", "500");
  evaluate("document.querySelector('.post-card:has(a[href*=demo0]) button[aria-label=\"Bookmark on this device\"]').scrollIntoView({block:'center'}); true");
  run("wait", "300");
  run("click", '.post-card:has(a[href*=demo0]) button[aria-label="Bookmark on this device"]');
  wait("document.querySelector('.post-card button[aria-label=\"Remove local bookmark\"]')");
  run("open", `${origin}/bookmarks`); wait("document.querySelector('main li')");
  check("document.querySelector('main li').textContent.includes('A quiet morning')", "Anonymous bookmark is available on its own page");
  click("Remove A quiet morning in the mountains from local bookmarks");
  check("!document.querySelector('main li')", "Local bookmark can be removed");
  run("open", origin); wait("document.querySelector('.post-card')");
  click("Pin collection Aesthetic");
  check("document.querySelector('.collection-link').textContent === 'Aesthetic'", "Pinned collection moves first");
  run("reload"); wait("document.querySelector('[aria-label=\"Unpin collection Aesthetic\"]')");
  click("filters"); wait("document.querySelector('[role=dialog]')");
  run("find", "role", "switch", "click", "--name", "Self", "--exact");
  click("apply"); wait("document.querySelector('.active-filters')");
  check("document.querySelector('.active-filters').textContent.includes('Text posts')", "Applied content filters appear as readable chips");
  wait("!document.querySelector('[role=dialog]')");
  click("Show text posts"); wait("!document.querySelector('.active-filters')");
  wait("document.querySelector('.feed-controls [aria-label=filters]').getAttribute('aria-pressed') === 'false'");
  check("document.querySelector('.feed-controls [aria-label=filters]').getAttribute('aria-pressed') === 'false'", "Removing last chip clears active filter state");
  wait("document.querySelectorAll('.post-card').length === 5");
  const updated = structuredClone(listing);
  updated.data.children.unshift({ ...updated.data.children[1], data: { ...updated.data.children[1].data, id: "fresh", name: "t3_fresh", title: "A fresh perspective", permalink: "/r/Design/comments/fresh/new/" } });
  run("network", "unroute", "*reddit.com*");
  run("network", "route", "*reddit.com*", "--body", JSON.stringify(updated));
  click("Refresh feed"); wait("document.querySelector('.feed-update')");
  check("document.querySelectorAll('.post-card').length === 5 && !document.querySelector('.post-card:has(a[href*=fresh])')", "New posts wait for explicit acceptance without replacing the feed");
  run("click", ".feed-update"); wait("document.querySelector('.post-card:has(a[href*=fresh])')");
  check("!document.querySelector('.feed-update')", "Accepting new posts updates the feed and clears the notice");
  evaluate("scrollTo(0,800); true"); wait("document.querySelector('.back-to-top')");
  check("Math.abs(document.querySelector('.feed-controls').getBoundingClientRect().top - 72) < 2", "Reading toolbar stays below the header while scrolling");
  click("↑ Back to top"); wait("scrollY === 0");
  const communities = { kind: "Listing", data: { after: null, children: [{ kind: "t5", data: { name: "t5_design", display_name: "Design", display_name_prefixed: "r/Design", title: "Thoughtful design", public_description: "Objects, spaces, and ideas worth exploring.", subscribers: 1200, url: "/r/Design/" } }] } };
  run("network", "unroute", "*reddit.com*");
  run("network", "route", "*reddit.com*", "--body", JSON.stringify(communities));
  run("open", `${origin}/search?q=design&type=sr`);
  wait("document.querySelector('#search-results a[href=\"/r/Design\"]')");
  check("document.querySelector('[role=tab][aria-selected=true]').textContent === 'Communities'", "Community results render without a people-only follow flag");
  run("focus", "#search-type-sr"); run("press", "ArrowRight");
  wait("document.querySelector('[role=tab][aria-selected=true]').textContent === 'People'");
  check("new URL(location.href).searchParams.get('type') === 'user'", "Search tabs support arrow-key navigation and update the URL");
  run("set", "viewport", "390", "844");
  run("open", `${origin}/settings`); wait("document.querySelector('.palette-choice')");
  click("Espresso theme");
  check("document.documentElement.scrollWidth <= innerWidth", "Mobile theme picker has no horizontal overflow");
  evaluate("document.querySelector('.reading-tuners').scrollIntoView({block:'center'}); true");
  check("document.documentElement.scrollWidth <= innerWidth", "Maximum mobile reading tuning has no horizontal overflow");
  console.log(`${checks} polish browser checks passed`);
} finally { run("close"); }
